apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server
  namespace: argocd
spec:
  project: default
  source:
    chart: metrics-server
    repoURL: https://kubernetes-sigs.github.io/metrics-server
    targetRevision: 3.10.0
    helm:
      releaseName: metrics-server
      parameters:                                                               
      - name: args[0]                                                           
        value: --kubelet-insecure-tls 
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kube-system